//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationPortal.Common
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EducationPortal.Common.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token has expired, please reload report to view it..
        /// </summary>
        public static string AccessTokenExpired {
            get {
                return ResourceManager.GetString("AccessTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact broker to activate your account..
        /// </summary>
        public static string ActivateAccount {
            get {
                return ResourceManager.GetString("ActivateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been activated successfully..
        /// </summary>
        public static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been added successfully..
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exists in team. You cannot complete task..
        /// </summary>
        public static string AffiliateNotExistsInTeam {
            get {
                return ResourceManager.GetString("AffiliateNotExistsInTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should contain digits only..
        /// </summary>
        public static string AllowNumberOnly {
            get {
                return ResourceManager.GetString("AllowNumberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already added leave on selected date and time range..
        /// </summary>
        public static string AlreadyAddedLeaved {
            get {
                return ResourceManager.GetString("AlreadyAddedLeaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave has been already approved or declined. Please refresh the page to get updated records..
        /// </summary>
        public static string AlreadyApprovedOrDeclined {
            get {
                return ResourceManager.GetString("AlreadyApprovedOrDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists. Please enter different value..
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists for selected category. Enter/select different value..
        /// </summary>
        public static string AlreadyExistsAffiliateEmail {
            get {
                return ResourceManager.GetString("AlreadyExistsAffiliateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! The username is already taken..
        /// </summary>
        public static string AlreadyExistUsername {
            get {
                return ResourceManager.GetString("AlreadyExistUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already imported. Please upload new file.
        /// </summary>
        public static string AlreadyImported {
            get {
                return ResourceManager.GetString("AlreadyImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task is already in running mode..
        /// </summary>
        public static string AlreadyInRunningMode {
            get {
                return ResourceManager.GetString("AlreadyInRunningMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already logged in..
        /// </summary>
        public static string AlreadyLoggedIn {
            get {
                return ResourceManager.GetString("AlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already logged out..
        /// </summary>
        public static string AlreadyLoggedOut {
            get {
                return ResourceManager.GetString("AlreadyLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doument already uploaded..
        /// </summary>
        public static string AlreadyUploaded {
            get {
                return ResourceManager.GetString("AlreadyUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another task is alreay in running mode..
        /// </summary>
        public static string AnotherTaskRunning {
            get {
                return ResourceManager.GetString("AnotherTaskRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter/select at least one {0}..
        /// </summary>
        public static string AtleastOneRecord {
            get {
                return ResourceManager.GetString("AtleastOneRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is black listed..
        /// </summary>
        public static string BlackListedLicense {
            get {
                return ResourceManager.GetString("BlackListedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t do this action. First do relative check in/check out..
        /// </summary>
        public static string CantDoAction {
            get {
                return ResourceManager.GetString("CantDoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t edit this leave. Leave has been approved/declined..
        /// </summary>
        public static string CantEditLeave {
            get {
                return ResourceManager.GetString("CantEditLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t start task due to office timeout..
        /// </summary>
        public static string CantStartTask {
            get {
                return ResourceManager.GetString("CantStartTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} combination with this {1} already exists. Try to choose different value..
        /// </summary>
        public static string CombinationExists {
            get {
                return ResourceManager.GetString("CombinationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration confirmation has been already done..
        /// </summary>
        public static string ConfirmationAlreadyDone {
            get {
                return ResourceManager.GetString("ConfirmationAlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration confirmation has been already done. Please wait until system administrator approve your registration account..
        /// </summary>
        public static string ConfirmationAlreadyDonePendingWithSystem {
            get {
                return ResourceManager.GetString("ConfirmationAlreadyDonePendingWithSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists {1}..
        /// </summary>
        public static string CustomMessageForExistence {
            get {
                return ResourceManager.GetString("CustomMessageForExistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than current date..
        /// </summary>
        public static string DateGreaterthanCurrent {
            get {
                return ResourceManager.GetString("DateGreaterthanCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  should not be greater than current date..
        /// </summary>
        public static string DateNotGreaterthanCurrent {
            get {
                return ResourceManager.GetString("DateNotGreaterthanCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been deleted successfully..
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some file(s) not able to deleted due to unexpected error..
        /// </summary>
        public static string DeletedError {
            get {
                return ResourceManager.GetString("DeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! You can not view the detail..
        /// </summary>
        public static string DenyDetail {
            get {
                return ResourceManager.GetString("DenyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document has been uploaded successfully..
        /// </summary>
        public static string DocumentUploadedSuccess {
            get {
                return ResourceManager.GetString("DocumentUploadedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do lunch time-in to start the task..
        /// </summary>
        public static string DoLunchTimeIn {
            get {
                return ResourceManager.GetString("DoLunchTimeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do office time-in to start the task..
        /// </summary>
        public static string DoOfficeTimeIn {
            get {
                return ResourceManager.GetString("DoOfficeTimeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, &lt;br/&gt; {0} shared document with you..
        /// </summary>
        public static string DoucumentSharedEmailContent {
            get {
                return ResourceManager.GetString("DoucumentSharedEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! The record has been deleted from the system..
        /// </summary>
        public static string Drop {
            get {
                return ResourceManager.GetString("Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has been sent successfully..
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry saved successfully..
        /// </summary>
        public static string EntrySaved {
            get {
                return ResourceManager.GetString("EntrySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured, please try again..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured, please contact administrator..
        /// </summary>
        public static string ErrorContactAdmin {
            get {
                return ResourceManager.GetString("ErrorContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured while {0}..
        /// </summary>
        public static string ErrorWithMessage {
            get {
                return ResourceManager.GetString("ErrorWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all required fields..
        /// </summary>
        public static string FieldsRequired {
            get {
                return ResourceManager.GetString("FieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists..
        /// </summary>
        public static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file! Please upload valid attachment(s),{0} file extension not allowed..
        /// </summary>
        public static string FileNotAllowed {
            get {
                return ResourceManager.GetString("FileNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not available you are trying to download..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in file content length..
        /// </summary>
        public static string FileUploadInvalidLength {
            get {
                return ResourceManager.GetString("FileUploadInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload file less than {0}..
        /// </summary>
        public static string FileUploadSize {
            get {
                return ResourceManager.GetString("FileUploadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only upload file like {0}..
        /// </summary>
        public static string FileUploadWithInvalidExtension {
            get {
                return ResourceManager.GetString("FileUploadWithInvalidExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date should be less than or equal to - to date..
        /// </summary>
        public static string FromDateToDate {
            get {
                return ResourceManager.GetString("FromDateToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load google analytics report data, please try again after some time..
        /// </summary>
        public static string GoogleAnalyticsError {
            get {
                return ResourceManager.GetString("GoogleAnalyticsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} imported successfully..
        /// </summary>
        public static string Imported {
            get {
                return ResourceManager.GetString("Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select valid user type..
        /// </summary>
        public static string IncorrectUserType {
            get {
                return ResourceManager.GetString("IncorrectUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been added successfully..
        /// </summary>
        public static string InsertSuccessFully {
            get {
                return ResourceManager.GetString("InsertSuccessFully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder\file name can&apos;t contain any of the following characters: \ / : * ? &quot; &lt; &gt; |.
        /// </summary>
        public static string InvalidChars {
            get {
                return ResourceManager.GetString("InvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file! Please upload attachment(s) with an extension like {0}..
        /// </summary>
        public static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File you uploaded is not valid as per selection on form..
        /// </summary>
        public static string InvalidFileUpload {
            get {
                return ResourceManager.GetString("InvalidFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} link is invalid..
        /// </summary>
        public static string InvalidLink {
            get {
                return ResourceManager.GetString("InvalidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} model state is not valid. Please try again.
        /// </summary>
        public static string InvalidModelState {
            get {
                return ResourceManager.GetString("InvalidModelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selcted folder not exists..
        /// </summary>
        public static string InvalidRootFolder {
            get {
                return ResourceManager.GetString("InvalidRootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid web URL..
        /// </summary>
        public static string InValidWebURL {
            get {
                return ResourceManager.GetString("InValidWebURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more {0} are in use..
        /// </summary>
        public static string IsInUse {
            get {
                return ResourceManager.GetString("IsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid..
        /// </summary>
        public static string IsInValid {
            get {
                return ResourceManager.GetString("IsInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to approve/decline leave..
        /// </summary>
        public static string LeaveApprovalPermisson {
            get {
                return ResourceManager.GetString("LeaveApprovalPermisson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave has been approved successfully..
        /// </summary>
        public static string LeaveApproved {
            get {
                return ResourceManager.GetString("LeaveApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave date has been passed. You can&apos;t approve or decline leave..
        /// </summary>
        public static string LeaveDatePassed {
            get {
                return ResourceManager.GetString("LeaveDatePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave has been declined successfully..
        /// </summary>
        public static string LeaveDeclined {
            get {
                return ResourceManager.GetString("LeaveDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave has been deleted or does not exitsts..
        /// </summary>
        public static string LeaveDoesNotExists {
            get {
                return ResourceManager.GetString("LeaveDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be less than or equal to {1}..
        /// </summary>
        public static string LessThanOrEqualTo {
            get {
                return ResourceManager.GetString("LessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {1} characters allowed for {0}..
        /// </summary>
        public static string MaxAllowedLength {
            get {
                return ResourceManager.GetString("MaxAllowedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file(s) must be less than {0} MB..
        /// </summary>
        public static string MaxFileSizeExceeded {
            get {
                return ResourceManager.GetString("MaxFileSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {2} to {1} characters long..
        /// </summary>
        public static string MinMaxAllowedLength {
            get {
                return ResourceManager.GetString("MinMaxAllowedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number should be at least 10 characters long..
        /// </summary>
        public static string MobileLength {
            get {
                return ResourceManager.GetString("MobileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password cannot be same as old password..
        /// </summary>
        public static string NewPasswordCanNotBeSame {
            get {
                return ResourceManager.GetString("NewPasswordCanNotBeSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to add {0}(s).
        /// </summary>
        public static string NoAddPermission {
            get {
                return ResourceManager.GetString("NoAddPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to delete {0}(s).
        /// </summary>
        public static string NoDeletePermission {
            get {
                return ResourceManager.GetString("NoDeletePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to download {0}(s).
        /// </summary>
        public static string NoDownloadPermission {
            get {
                return ResourceManager.GetString("NoDownloadPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to edit {0}(s).
        /// </summary>
        public static string NoEditPermission {
            get {
                return ResourceManager.GetString("NoEditPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been added successfully. Email was not sent successfully..
        /// </summary>
        public static string NoEmailSent {
            get {
                return ResourceManager.GetString("NoEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to print {0}(s).
        /// </summary>
        public static string NoPrintPermission {
            get {
                return ResourceManager.GetString("NoPrintPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.
        /// </summary>
        public static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found to export data..
        /// </summary>
        public static string NoRecordtoExport {
            get {
                return ResourceManager.GetString("NoRecordtoExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be same. Try to choose/enter different value..
        /// </summary>
        public static string NoSameValues {
            get {
                return ResourceManager.GetString("NoSameValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to view requested page..
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this action..
        /// </summary>
        public static string NotAutorizedAction {
            get {
                return ResourceManager.GetString("NotAutorizedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not entered/selected any of required field(s)..
        /// </summary>
        public static string NotEnteredRequiredField {
            get {
                return ResourceManager.GetString("NotEnteredRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t exists or has been deleted..
        /// </summary>
        public static string NotExists {
            get {
                return ResourceManager.GetString("NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t exists..
        /// </summary>
        public static string NotExistsUser {
            get {
                return ResourceManager.GetString("NotExistsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task is not in running mode.
        /// </summary>
        public static string NotInRunningMode {
            get {
                return ResourceManager.GetString("NotInRunningMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not verified by system, please contact administrator..
        /// </summary>
        public static string NotVerifiedBySystem {
            get {
                return ResourceManager.GetString("NotVerifiedBySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to view  {0}(s).
        /// </summary>
        public static string NoViewPermission {
            get {
                return ResourceManager.GetString("NoViewPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} to {2}..
        /// </summary>
        public static string NumericRange {
            get {
                return ResourceManager.GetString("NumericRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password do not match with our data, enter proper value..
        /// </summary>
        public static string OldPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("OldPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed date for open house must be 2 weeks later of current date..
        /// </summary>
        public static string OpenHouseInvalidDate {
            get {
                return ResourceManager.GetString("OpenHouseInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t open {0} in multiple tabs at the same time..
        /// </summary>
        public static string OpenTab {
            get {
                return ResourceManager.GetString("OpenTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department and parent department cannot be same..
        /// </summary>
        public static string ParentChildCanNotSame {
            get {
                return ResourceManager.GetString("ParentChildCanNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Confirm password&apos; and &apos;password&apos; do not match..
        /// </summary>
        public static string PasswordDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be 10 digit number..
        /// </summary>
        public static string PhoneLength {
            get {
                return ResourceManager.GetString("PhoneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration has been completed successfully..
        /// </summary>
        public static string RegistrationComplete {
            get {
                return ResourceManager.GetString("RegistrationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has been successfully resent to your registered email address..
        /// </summary>
        public static string ResendEmail {
            get {
                return ResourceManager.GetString("ResendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password email has been sent to your registered email address..
        /// </summary>
        public static string ResetPasswordMail {
            get {
                return ResourceManager.GetString("ResetPasswordMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is in use you can not update it as inactive..
        /// </summary>
        public static string RoleExistsInUser {
            get {
                return ResourceManager.GetString("RoleExistsInUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select file to upload..
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least 1 user..
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session was expired, please make entries again and save the record..
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} status has been changed successfully..
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your task is in running mode. Please stop your task..
        /// </summary>
        public static string StopTaskFirst {
            get {
                return ResourceManager.GetString("StopTaskFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been changed successfully..
        /// </summary>
        public static string SuccessChanged {
            get {
                return ResourceManager.GetString("SuccessChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been successfully logged out..
        /// </summary>
        public static string SuccessLogOut {
            get {
                return ResourceManager.GetString("SuccessLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset successfully..
        /// </summary>
        public static string SuccessResetPassword {
            get {
                return ResourceManager.GetString("SuccessResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You doesn&apos;t have permission to perform this action or task does not exists..
        /// </summary>
        public static string TaskNotExistsOrNoPermission {
            get {
                return ResourceManager.GetString("TaskNotExistsOrNoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please change the status..
        /// </summary>
        public static string TaskStartStatus {
            get {
                return ResourceManager.GetString("TaskStartStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status {0} not allowed at {1} time..
        /// </summary>
        public static string TaskStatusNotAllowed {
            get {
                return ResourceManager.GetString("TaskStatusNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been updated successfully..
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is wrong..
        /// </summary>
        public static string WrongEmailPassword {
            get {
                return ResourceManager.GetString("WrongEmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! You can&apos;t activate selected listing please contact administartor..
        /// </summary>
        public static string WrongListingSelected {
            get {
                return ResourceManager.GetString("WrongListingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uername is wrong..
        /// </summary>
        public static string WrongUsername {
            get {
                return ResourceManager.GetString("WrongUsername", resourceCulture);
            }
        }
    }
}
